name: irgs
channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - python=3.8.18
  - pip=23.3.1
  - ffmpeg=4.2.2
  - pillow
  - wheel
  - typing_extensions=4.9.0
  - pytorch::pytorch=2.0.0
  - pytorch::torchvision=0.15.0
  - pytorch::torchaudio=2.0.0
  - pytorch-cuda=11.8
  - cuda
  - conda-forge::gcc_linux-64=11
  - conda-forge::gxx_linux-64=11
  - conda-forge::cmake
  - conda-forge::ninja
  - conda-forge::eigen
  - pip:
    - open3d==0.18.0
    - mediapy==1.1.2
    - lpips==0.1.4
    - scikit-image==0.21.0
    - tqdm==4.66.2
    - trimesh==4.3.2
    - plyfile
    - opencv-python
    - dearpygui
    - kornia
    - numpy
    - matplotlib
    - pyexr
    - submodules/diff-surfel-rasterization
    - submodules/simple-knn
    - submodules/raytracing
    - submodules/surfel_tracer
